### ISSUE TITLE
user_define 頁面_當沒有任何飲品的時候把 新增品項以下的東西隱藏

### ISSUE THREAD

**Issue by mkx777** [dannyh79/TonightLetsDrinkDrink#39]
示意圖
原先狀況

![image](https://user-images.githubusercontent.com/48974903/60072893-7ace5b00-9751-11e9-9276-0d27bffced43.png)

變成這樣

![image](https://user-images.githubusercontent.com/48974903/60072922-95083900-9751-11e9-9262-217b7dfccd5d.png)

並且讓增加品項的按鈕不能連續點擊

**Comment by dannyh79** [comment]
感謝提供。已於 06/26 merge 變更。
