### ISSUE TITLE
手機版點選 input 畫面會自動放大

### ISSUE THREAD

**Issue by mkx777** [dannyh79/TonightLetsDrinkDrink#83]
禁止自動放大的功能(手機版自製調酒點選 input 會自動放大一點網頁)
造成使用不便(要自行縮小網頁)
加入主畫面螢幕的功能(加入主畫面以後可以更方便的全螢幕瀏覽)

**Comment by dannyh79** [comment]
Resolved in Release v1.1.0 (#104).
